/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_v1_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device */
        get: operations["get_device_api_v1_devices__device_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_api_v1_devices__device_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleet/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fleet Summary */
        get: operations["fleet_summary_api_v1_fleet_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_api_v1_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alert */
        Alert: {
            /** Device Id */
            device_id: string;
            /** Hostname */
            hostname: string | null;
            /** Id */
            id: number;
            /** Last Value */
            last_value: number | null;
            /** Message */
            message: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Resolved At */
            resolved_at: string | null;
            /** Rule */
            rule: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "warning" | "critical";
        };
        /** AlertCounts */
        AlertCounts: {
            /** Critical */
            critical: number;
            /** Warning */
            warning: number;
        };
        /** AlertList */
        AlertList: {
            /** Items */
            items: components["schemas"]["Alert"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** DeviceDetail */
        DeviceDetail: {
            /** Cpu Temperature C */
            cpu_temperature_c: number | null;
            /** Cpu Usage Percent */
            cpu_usage_percent: number | null;
            /** Device Id */
            device_id: string;
            /** Disk Usage Percent */
            disk_usage_percent: number | null;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /** Hostname */
            hostname: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            latest: components["schemas"]["LatestReading"] | null;
            /** Open Alert Count */
            open_alert_count: number;
            /** Open Alerts */
            open_alerts: components["schemas"]["Alert"][];
            /** Os */
            os: string;
            /** Packet Loss Percent */
            packet_loss_percent: number | null;
            /** Ram Usage Percent */
            ram_usage_percent: number | null;
            /** Services */
            services: components["schemas"]["ServiceStatus"][];
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "warning" | "critical" | "offline";
            /** Uptime Seconds */
            uptime_seconds: number | null;
        };
        /** DeviceList */
        DeviceList: {
            /** Items */
            items: components["schemas"]["DeviceSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** DeviceSummary */
        DeviceSummary: {
            /** Cpu Temperature C */
            cpu_temperature_c: number | null;
            /** Cpu Usage Percent */
            cpu_usage_percent: number | null;
            /** Device Id */
            device_id: string;
            /** Disk Usage Percent */
            disk_usage_percent: number | null;
            /** Hostname */
            hostname: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /** Open Alert Count */
            open_alert_count: number;
            /** Os */
            os: string;
            /** Packet Loss Percent */
            packet_loss_percent: number | null;
            /** Ram Usage Percent */
            ram_usage_percent: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "warning" | "critical" | "offline";
            /** Uptime Seconds */
            uptime_seconds: number | null;
        };
        /** FleetSummary */
        FleetSummary: {
            devices: components["schemas"]["StatusCounts"];
            /** Fullest Disks */
            fullest_disks: components["schemas"]["RankedDevice"][];
            /** Hottest */
            hottest: components["schemas"]["RankedDevice"][];
            open_alerts: components["schemas"]["AlertCounts"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /** LatestReading */
        LatestReading: {
            /** Containers Running */
            containers_running: number;
            /** Containers Stopped */
            containers_stopped: number;
            /** Disk Total Gb */
            disk_total_gb: number;
            /** Disk Used Gb */
            disk_used_gb: number;
            /** Load 1M */
            load_1m: number;
            /** Net Interface */
            net_interface: string;
            /** Ram Total Mb */
            ram_total_mb: number;
            /** Ram Used Mb */
            ram_used_mb: number;
            /** Rx Rate Bps */
            rx_rate_bps: number | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Tx Rate Bps */
            tx_rate_bps: number | null;
        };
        /** MetricPoint */
        MetricPoint: {
            /** Max */
            max?: number | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Value */
            value: number | null;
        };
        /** MetricSeries */
        MetricSeries: {
            /**
             * Bucket
             * @enum {string}
             */
            bucket: "raw" | "1h" | "1d";
            /** Device Id */
            device_id: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Metric
             * @enum {string}
             */
            metric: "cpu" | "temperature" | "ram" | "disk" | "packet_loss" | "rx_rate" | "tx_rate";
            /** Points */
            points: components["schemas"]["MetricPoint"][];
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Unit */
            unit: string;
        };
        /** RankedDevice */
        RankedDevice: {
            /** Device Id */
            device_id: string;
            /** Hostname */
            hostname: string;
            /** Value */
            value: number;
        };
        /** ServiceStatus */
        ServiceStatus: {
            /**
             * Changed At
             * Format: date-time
             */
            changed_at: string;
            /** Name */
            name: string;
            /** State */
            state: string;
        };
        /** StatusCounts */
        StatusCounts: {
            /** Critical */
            critical: number;
            /** Healthy */
            healthy: number;
            /** Offline */
            offline: number;
            /** Total */
            total: number;
            /** Warning */
            warning: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                state?: "open" | "resolved" | "all";
                device_id?: string | null;
                severity?: ("warning" | "critical") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_api_v1_devices_get: {
        parameters: {
            query?: {
                status?: ("healthy" | "warning" | "critical" | "offline") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_api_v1_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDetail"];
                };
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_api_v1_devices__device_id__metrics_get: {
        parameters: {
            query: {
                metric: "cpu" | "temperature" | "ram" | "disk" | "packet_loss" | "rx_rate" | "tx_rate";
                from?: string | null;
                to?: string | null;
                bucket?: ("raw" | "1h" | "1d") | null;
            };
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricSeries"];
                };
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fleet_summary_api_v1_fleet_summary_get: {
        parameters: {
            query?: {
                top?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_api_v1_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
